DATA_DIRECTORY: /volatile/clas12/rmilton/RICH_data_hadrons_fixtables_withbestch/ # Directory containing the input root files
SAVE_DIRECTORY: /volatile/clas12/rmilton/processed_RICH_data_sector4_positives_hadrons_fixtables_min10hits_withbestch/
SAVE_FILE_NAME: preprocessed_RICH_sector4_positives_kaons_pions
SECTOR: 4
MAX_NUM_TRAJECTORIES: 1
MIN_HIT_MULTIPLICITY: 10
MIN_MOMENTUM: 1
MAX_MOMENTUM: 12
USE_NEGATIVE_CHARGE: False
USE_POSITIVE_CHARGE: True
TRAIN_TEST_SPLIT: True
TRAINING_FRACTION: 0.75