EPOCHS: 200
BATCH_SIZE: 64
LEARNING_RATE: 1e-5
HIT_DIMENSIONS: 3
GLOBAL_DIMENSIONS: 6
HIDDEN_DIMENSIONS: 64
NUMBER_CLASSES: 2
k: 10
MODEL_SAVE_DIRECTORY: "/volatile/clas12/rmilton/RICH_models_LR1E-5_64hiddendimensions_200epochs_0.1validationsplit_dropout0.2_3.15GeVmomentumcut/"
VALIDATION_SPLIT: 0.1
DROPOUT_RATE: 0.2